---
title: Manuscript 1
author:
  - name: Andreas Ludvig Ohm Svendsen
    orcid: 0000-0001-8050-6447
    corresponding: true 
    email: alosvendsen@health.sdu.dk
    roles:
      - Investigation
      - Project administration
      - Software
      - Visualization
    affiliations:
      - SDU
  - name: Erkka Järvinen
    affiliations: 
      - SDU?
    corresponding: false
  - name: Tore B. Stage
    affiliations: 
      - SDU
    corresponding: false
keywords:
  - 3D primary human hepatocytes
  - Inflammation
  - Drug metabolism
abstract: |
  This is an abstract ...
plain-language-summary: |
  Some plain language summary...
key-points:
  - First keypoint.
  - Second keypoint.
date: last-modified
bibliography: references.bib
csl: vancouver.csl
number-sections: false
reference-location: margin
lightbox: true
notebook-links: global
---

## Introduction

Inflammation is a complex biological response that is pivotal in various pathological conditions. These range from systemic inflammatory diseases, such as rheumatoid arthritis and sepsis, to lower-grade chronic inflammatory states such as type 2 diabetes mellitus. Given the prevalence of systemic inflammation, understanding its interaction with drug metabolism is of substantial clinical relevance.

Drug-metabolizing enzymes and transporters (DMETs), predominantly found in hepatocytes within the liver, are central to the biotransformation of a wide variety of compounds. Inflammation has been shown to modulate the activity of these DMETs, a phenomenon that could potentially affect the pharmacokinetics of numerous medications. For individuals with altered inflammatory status—whether due to a chronic condition like diabetes or an acute event like sepsis—this modulation can have significant implications. It may necessitate adjustments in drug dosages to avoid adverse effects or therapeutic failure.

Previous research has provided valuable insights into the effects of inflammation on DMETs, but a clear correlation between in vitro studies and clinical observations remains elusive. For instance Dunvald et al. [@dunvald] conducted a comprehensive review of the clinical and in vitro evidence on inflammation-mediated modulation of DMETs and the impact on drug metabolism in humans. They found that in vitro studies in primary human hepatocytes revealed strong evidence of downregulation of key cytochrome P450 (CYP) enzymes by inflammatory cytokines such as IL-6 and IL-1β. However, these studies often employed supraphysiological cytokine doses, which may not accurately represent the inflammatory conditions observed in patients.

Levels of IL-6 and IL-1β in healthy individuals are generally low, with reports in range of \~10pg/ml in adults for IL-6, and \~2.5 pg/ml IL-1β in adults [@kim2011; @kleiner2013; @said2021; @strand2020]. In contrast, cytokine levels may be considerably elevated with IL-6 levels of \~140 pg/mL, and IL-1β [levels of \~100 pg/mL]{.underline}, among patients with rheumatoid arthritis or SLE [@umare2014] to more than 1 ng/mL of IL-6 for patients with acute inflammation caused by sepsis [@franco2019]. These variations in cytokine levels, which span a wide range in different pathological states, highlight the complex and dynamic nature of inflammation and underscore the need for research that considers this variability when investigating the effects of inflammation on drug-metabolizing enzymes.

The median IL-6 values (IQR) in the control, sepsis, and septic shock groups were 23.6 (11.2–43.5), 89.9 (45.2–272.6), and 1378.6 (256.4–11,062.1) pg/mL

<https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-019-4618-7>

Recently, 3D primary human hepatocytes (PHH) have challenged 2D PHH as a more physiologically relevant culture method of PHH. 3D culture leads to more stable cell cultures that retain their hepatic phenotype for extended periods of time [@bell2016]. Consequently, this 3D PHH have been shown to predict CYP induction and hepatotoxicity more accurately than 2D PHH [@bell2018; @järvinen2023]. Historically, 2D PHH have been utilized to study the effect of drugs and inflammation on hepatocyte/liver function. However, the inherent limitations of 2D cultures, primarily their inability to maintain the physiological phenotype and liver-specific functions of hepatocytes, have prompted a shift towards the 3D liver spheroid models. This model is increasingly recognized for their physiological relevance and stability, offering a more accurate representation of hepatic responses. The 3D liver spheroids preserve liver cell phenotypes and functions over extended periods, thereby enhancing the reliability of drug-induced liver injury predictions and disease mechanism investigations. This advancement positions 3D liver spheroids as potentially the new standard for in vitro hepatocyte studies, while still being suitable for a high throughput setting, and financially accessible as opposed to even more advanced liver models (ref for last part) [@ingelman-sundberg; @dunvald] . Another claim for the lack of correlation discussed in the review by AC et al. is that there might be methodological limitations to the widespread use of 2D models of PHHs [@dunvald].

We aimed to utilize 3D primary human hepatocytes [@bell2016] to study the impact of physiologically relevant concentrations of cytokines on CYP expression and activity. This may help further our understanding of the impact of inflammation on clinical drug metabolism among patients with inflammation. This, in turn, may inform more precise and adaptive prescribing strategies for patients in various inflammatory states.

## Methods

### 3D spheroid culture of PHHs

#### Materials

All necessary components for cell culture, including the medium, supplements, and compounds, were acquired from Thermo Fisher Scientific, unless stated otherwise.

#### Cell source and preparation

Three lots of cryopreserved primary human hepatocytes, specifically Hu8345-A, Hu8373-A and Hu8381, were procured from Thermo Fisher Scientific (Waltham, MA). All necessary cell culture reagents were sourced from the same supplier. All PHHs were qualified for spheroid formation per the manufacturer.

#### Spheroid formation and maintenance

The spheroid culture followed an adapted protocol from a previous study [@bell2016]. In short 1500 hepatocytes per well in ultra-low attachment 96-well plates. Following seeding, the plates were centrifuged for 2 minutes at 200g. Subsequently, the plates were incubated at 37°C with 5% CO2.

On day 0 cells were seeded in culture medium, totaling 100 μL per well, consisting of 5% fetal bovine serum, 1 μM dexamethasone, 5 μg/mL human recombinant insulin, 100 U/mL penicillin, 100 μg/mL streptomycin, 2 mM L-glutamine, and 15 mM HEPES in Williams' E medium.

After spheroid formation the seeding medium was replaced with FBS free maintenance medium. This medium comprised 0.1 μM dexamethasone, 10 μg/mL human recombinant insulin, 5.5 μg/mL transferrin, 6.7 ng/mL selenium, 100 U/mL penicillin, 100 μg/mL streptomycin, and 2 mM L-glutamine in Williams' E medium. This FBS washout with maintenance medium was done with a 70% medium change on days 5-7. `For donor 1 (Hu8345-A) the maintenance also contained 5.35 μg/mL linoleic acid, 1.25 mg/mL bovine serum albumin and 15 mM HEPES. These supplements are, however, no longer recommended by the manufacturer`[^1]`.`

[^1]: Skip this?

Detailed descriptions of the spheroid culture process, as well as donor information, are available in the supplementary materials (Table SX).

### Treatments

Treatment with proinflammatory cytokines commenced on day 8 post seeding. The spheroids were exposed to IL-6 and IL-1β at concentrations of 0.01, 0.1, 1, and 10 ng/ml, alongside a vehicle control (0.1% bovine serum albumin in PBS). The cytokine treatments and vehicle control were diluted 1:1000 in the culture medium before administration.Re-dosing was done every other day for long-term cultures.

### Spheroid viability and morphology

The viability of the spheroids was monitored by measuring their ATP content, using the luminiscence CellTiter-Glo 3D assay from Promega (Madison, WI). Quantification of ATP was done using an ATP (from Thermo Fisher Scientific) standard curve. Viability was assessed every 2-3 days throughout the experiments.

In addition to viability testing, the morphology of the spheroids was monitored. Imaging was done every second or third day, aligning with the viability assays. The spheroids were imaged using a light microscope equipped with a 10X magnification lens and a digital camera from Motic (Hong Kong, China).

### RNA extraction, cDNA synthesis and qPCR

RNA was extracted using the phenol-chloroform method, following the manufacturer's protocol from Qiagen with minor modifications [@toni2018]. Each spheroid pool was treated with 1 mL of Qiazol (Qiagen) reagent for lysis, followed by co-precipitation with 15 μg of RNA grade glycogen (Thermo Fisher Scientific). The RNA pellet underwent three washes with 75% ethanol. Post-wash, a combination of heating and evaporation techniques was applied to remove residual ethanol and to facilitate the solubilization of the RNA pellet in water.

RNA integrity was assessed for a subset of samples[^2] using the Agilent BioAnalyzer, yielding RNA Integrity Number (RIN) values from 7 to 9.8. These values indicate high-quality RNA. Concentration of RNA were estimated utilizing the NanoDrop spectrophotometer.

[^2]: Dog ikke fra nogle af disse 3 donorer, så måske bedre med: To assess the integrity of the RNA, we evaluated the RNA Integrity Number (RIN) for a subset of samples, which yielded values ranging from 7 to 9.8.\
    \
    To validate the RNA extraction method, we assessed the RNA Integrity Number (RIN) using the Agilent BioAnalyzer for a subset of samples not derived from the donors discussed in this article. These assessments yielded RIN values between 7 and 9.8, indicative of high-quality RNA.

Approximately 500 ng of extracted RNA was used for cDNA synthesis. This process was performed using the High-Capacity cDNA Reverse Transcription Kit with RNase Inhibitor (Thermo Fisher Scientific).

For qPCR, 10 ng of cDNA, based on the initial RNA concentration, was utilized for each reaction. The reactions were set up in a 10 μL volume containing TaqMan Universal Master Mix II and target-specific TaqMan assays (detailed in Supplementary Methods). The qPCR was run for 40 cycles, following the manufacturer's guidelines (Thermo Fisher Scientific). The PCR plate sample maximization method was applied[@derveaux2010], and a stable reference gene as well as no template controls and no reverse transcriptase controls was included in each plate.

In the analysis of mRNA expression, the relative quantity was calculated by first determining the delta Cq ((\Delta C_q)) for each sample. This was achieved by subtracting the mean Cq of the control group from the mean Cq of the replicates of each sample. The relative quantity was then computed using the formula (2\^{\Delta C_q}). For normalization, the relative quantity of the target gene in each sample was divided by the relative quantity of the reference gene (GAPDH or TBP). The average normalized expression for each biological group was subsequently calculated.

### Activity

To assess the activity of CYP3A4 (maybe otheres also), an experiment was conducted using midazolam as a substrate in spheroids derived from donors 2 and 3, evaluated on day 12. Midazolam (Toronto Research Chemicals, Toronto, ON, Canada), was prepared as a 6,000× stock solution in DMSO. The final DMSO concentration in the enzyme activity assays was maintained at 0.15%. Prior to the introduction of midazolam to the spheroids, the cells underwent three washes with 100 μL of maintenance medium. Between washes, the residual volume was kept at 20 μL, and before the final wash, the spheroids were incubated for 2 hours in a cell culture incubator.

The concentration of midazolam in the assay was set at 10 μM, with a total volume of 100 μL per well. For the analysis, triplicate samples, each comprising a ~~spheroid~~ and medium from a single well, were collected at 0.5 (8 hours for other enzymes) hours post midazolam treatment. These samples were then stored at -80°C until further analysis. The specific methods used for the metabolite analysis of these samples are detailed in the supplementary material.

### Quantitative analysis of proteins via LC-MS with selective immunoprecipitation

The quantification of human CYP ~~and transporter~~ proteins was performed using a targeted liquid chromatography-mass spectrometry approach, incorporating selective immunoprecipitation of peptides, as previously described[@weiß2018]. Uniform numbers of spheroids were employed in each analysis for consistency. In summary, spheroids were lysed in a buffer of 42 mM ammonium bicarbonate, containing 1.14 mM dithiothreitol and 9 mM iodoacetamide, and incubated for 15 minutes at 90°C, a method adapted from Savaryn et al. [@savaryn2020]. The lysates were then digested with MS-grade Pierce Trypsin Protease (Thermo Fisher Scientific) for 16 hours at 37°C. To halt the digestion, phenylmethanesulfonyl fluoride was added to each sample, achieving a final concentration of 1 mM and a total volume of 70 μL. A portion of the digested sample (25 μL) was then used for the immunoprecipitation of surrogate and internal standard peptides using triple X proteomics antibodies[@weiß2018]. These peptides were subsequently analyzed and quantified through LC-MS. The specific surrogate peptides employed for protein quantification and the LC-gradients are detailed in the supplementary material. For data processing, Skyline software (MACOSS Lab, University of Washington, Seattle, WA) and TraceFinder 4.1 (Thermo Fisher Scientific) were utilized.
